// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjM46cN2b9oHQK1RYGefgdeVducx-ijP8',
    appId: '1:542263575364:web:abe2389cbdbbdb91418d11',
    messagingSenderId: '542263575364',
    projectId: 'notemap-db',
    authDomain: 'notemap-db.firebaseapp.com',
    storageBucket: 'notemap-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJwiQwKxNUzxAGhMaY9AEgTkkxOj7lYMg',
    appId: '1:542263575364:android:fa5893bde7ca7663418d11',
    messagingSenderId: '542263575364',
    projectId: 'notemap-db',
    storageBucket: 'notemap-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARF8P1CF4buD0Dr6R0YNc3S2MeZ1Ha_4o',
    appId: '1:542263575364:ios:944798d1f21ebe58418d11',
    messagingSenderId: '542263575364',
    projectId: 'notemap-db',
    storageBucket: 'notemap-db.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARF8P1CF4buD0Dr6R0YNc3S2MeZ1Ha_4o',
    appId: '1:542263575364:ios:944798d1f21ebe58418d11',
    messagingSenderId: '542263575364',
    projectId: 'notemap-db',
    storageBucket: 'notemap-db.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjM46cN2b9oHQK1RYGefgdeVducx-ijP8',
    appId: '1:542263575364:web:94e9b2e37d8afd76418d11',
    messagingSenderId: '542263575364',
    projectId: 'notemap-db',
    authDomain: 'notemap-db.firebaseapp.com',
    storageBucket: 'notemap-db.appspot.com',
  );
}
